# Generated by Django 5.1.3 on 2025-12-16 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='date',
        ),
        migrations.AddField(
            model_name='studysession',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 18, 33, 51, 909468)),
        ),
    ]
